spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/newdb
    username: developer
    password: developer
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
    driver-class-name:  org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled: true
